targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          - "lib/models/*.dart"
        options:
          any_map: true
          field_rename: snake
