name: _core
publish_to: "none"

environment:
  sdk: ^3.0.0

dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.7
  derry: ^1.5.0
  json_serializable: ^6.7.1

scripts: ../scripts.yaml
